org.gradle.jvmargs=-Xmx4G

mod_version=6.0+1.21.4
maven_group=io.github.kosmx.bendy-lib
archives_base_name=bendy-lib

minecraft_version=1.21.4
loader_version=0.16.9

#Fabric api
fabric_version=0.112.2+1.21.4

#Forge thingy
forge_version=21.4.33-beta

#Other mods
player_anim_version=2.0.1+1.21.4
geckolib_version=4.8.3