architectury {
    common("neoforge", "fabric")
}

loom {
    accessWidenerPath = file("src/main/resources/bendylib.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"

    modCompileOnly "maven.modrinth:iris:8l8TrrQz"
    modCompileOnly "software.bernie.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}"
    modCompileOnly "dev.kosmx.player-anim:player-animation-lib-fabric:${rootProject.player_anim_version}"
    modCompileOnly "maven.modrinth:3dskinlayers:D4TLEY5I"
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    repositories {
        if (System.getenv("MAVEN_PASS") != null) {
            maven {
                url = 'https://maven.kosmx.dev/'
                credentials {
                    username = project.keys.maven_user
                    password = project.keys.kosmx_maven
                }
            }
        } else {
            mavenLocal()
        }


        if(System.getenv("GITHUB_ACTOR") != null) {
            maven {
                name = "GitHubPackages"
                url = "https://maven.pkg.github.com/kosmx/bendy-lib"
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}
